---
name: CI

on:
  push:
  workflow_dispatch:
    
jobs:
  update-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install wget -y
   
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
   
      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
   
      - name: Download binaries
        run: |
          wget -O OVMF_AA64.fd https://retrage.github.io/edk2-nightly/bin/RELEASEAARCH64_QEMU_EFI.fd
          wget -O OVMF_X64.fd https://retrage.github.io/edk2-nightly/bin/RELEASEX64_OVMF.fd
          wget -O OVMF_ARM.fd https://retrage.github.io/edk2-nightly/bin/RELEASEARM_QEMU_EFI.fd
          wget -O OVMF_IA32.fd https://retrage.github.io/edk2-nightly/bin/RELEASEIa32_OVMF.fd
   
      - name: Push
        run: |
          git config user.name '3uclid3'
          git config user.email '3uclid3@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/3uclid3/ovmf_binaries.git
          git fetch --all
          git add .
          git commit -m "Update binaries [ci skip]"
          git push origin main
   
